vich_uploader:
    db_driver: orm
    mappings:
        dish_image:
            uri_prefix: /uploads/dishes
            upload_destination: '%kernel.project_dir%/public/uploads/dishes'
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true

        order_document:
            uri_prefix: /uploads/orders
            upload_destination: '%kernel.project_dir%/public/uploads/orders'
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true